 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kong-proxy
  namespace:  {{ template "kong.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kong
  ingress:
   - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: dna-model-registry
            app.kubernetes.io/name: model-registry
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: model-registry 
   - ports:
     - port: 8000
       protocol: TCP                    
  policyTypes:
    - Ingress
---